# Surrogate Factory Notebook template  
## Chapter 3. Data Cleaning

Objectives of this template:
- Manage Missing Values
- Manage Outliers

### 0.- Define general config of the workflow

In [1]:
from IPython.display import display, HTML, JSON
from surrogate_factory.workflow import Workflow

workflow = Workflow("pipeline_config.yaml")
workflow.resume()

Setting up Workflow folders
Change to Data folder /home/c05279/Pipelines/Training/working_pipeline/data
tracker requested mlflow

Setting tracking uri: http://127.0.0.1:55000

2026-02-04 10:42:31.659999: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-02-04 10:42:31.670284: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1770198151.679967 1943504 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1770198151.682902 1943504 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1770198151.691792 1943504 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1770198151.691803 1943504 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1770198151.691805 1943504 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1770198151.691806 1943504 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2026-02-04 10:42:31.695044: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

Adding methods to Catalog
Workflow data loaded successfully.

/home/FlightPhysicsValidation/sFactoryTraining/lib/python3.10/site-packages/surrogate_factory/metadata.py:488: UserWarning: Loading data without validation as no schema was provided.
  warnings.warn("Loading data without validation as no schema was provided.")

### 4. Data Cleansing

In [2]:
workflow.import_metadata(stage_name="SF_3_Data_Cleansing")

Updating metadata for  Data_Cleansing
building_schema {'type': 'object', 'properties': {'Data_Cleansing': {'type': 'object', 'properties': {'Managing_Missing_Values': {'type': 'object', 'properties': {'output': {'type': 'array', 'items': {'type': 'object', 'properties': {'name': {'type': 'string'}, 'filling_value': {'type': 'integer'}}}}}}, 'Managing_Outliers': {'type': 'object', 'properties': {'output': {'type': 'array', 'items': {'type': 'object', 'properties': {'name': {'type': 'string'}, 'range': {'type': 'object', 'properties': {'min': {'type': 'number'}, 'max': {'type': 'number'}}}}}}}}}}}, '$schema': 'http://json-schema.org/draft-07/schema#', 'title': 'Data_Cleansing'}

VBox(children=(HTML(value='<h1>Data Cleansing</h1>'), VBox(children=(Accordion(children=(VBox(children=(Accord…

In [3]:
outputFilename = workflow.config['job_name'] + '_raw_dataset.csv'
Dataset = workflow.load_data(outputFilename)

In [4]:
Dataset.describe()

,Pin_D,R_DextDint,Male_Dt,Male_RoD,angle_env_reduc0,angle_env_reduc1,Female_RoD,Female_Dt,pin_doD,gap,RF_Lug1,RF_Lug2,RF_Pin
count,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,120000.000000,101319.000000,106861.000000,102198.000000
mean,42.385447,1.501177,5.400594,1.497407,90.466583,89.781845,1.500182,5.409903,0.497773,8.494592,1.950749,1.895538,1.848081
std,21.651458,0.289718,2.651361,0.404920,51.938086,51.913401,0.404027,2.657618,0.230556,3.737999,3.049268,2.816210,1.616424
min,5.005436,1.000015,0.800351,0.800032,0.010986,0.009613,0.800144,0.800912,0.100006,2.000744,0.100002,0.100003,0.100003
25%,23.623686,1.251204,3.110572,1.146322,45.843372,45.097160,1.151336,3.102413,0.297563,5.286288,0.388470,0.404432,0.535352
50%,42.344503,1.500624,5.402632,1.494569,90.533524,89.776154,1.501469,5.417670,0.496564,8.477510,0.939790,0.958089,1.339560
75%,61.213164,1.752005,7.687761,1.846748,135.769901,134.611874,1.849740,7.721636,0.697734,11.714022,2.225345,2.198040,2.770053
max,79.999428,1.999973,9.999684,2.199915,179.993134,179.993134,2.199995,9.999649,0.899988,14.999504,49.904800,45.727700,8.198120

#### 4.1 Managing missing values

In [5]:
from data_cleansing.manage_missing import replace_missing_values
Dataset_cleaned = replace_missing_values(workflow, Dataset)
Dataset_cleaned

Setting current step ['metadata', 'Data_Cleansing', 'Managing_Missing_Values']

/home/c05279/Pipelines/Training/working_pipeline/python_nodes_library/data_cleansing/manage_missing.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  input_table[v['name']].fillna(v['filling_value'], inplace=True)

,Pin_D,R_DextDint,Male_Dt,Male_RoD,angle_env_reduc0,angle_env_reduc1,Female_RoD,Female_Dt,pin_doD,TypeLC,gap,mat,RF_Lug1,RF_Lug2,RF_Pin
0,27.224426,1.913879,5.478052,1.885291,178.582764,113.170166,0.834949,2.553638,0.402100,UL/LL,11.398499,MAT1,0.822762,2.115400,0.441427
1,15.322571,1.879211,4.826685,1.687732,113.807373,11.656494,1.255359,5.262427,0.408740,UL/LL,6.542542,MAT1,0.290441,0.182754,0.160779
2,40.108185,1.874359,2.475867,1.983685,90.082397,154.725952,1.547809,4.331702,0.728247,UL/LL,8.051300,MAT1,3.869550,1.416690,0.844316
3,27.281075,1.748955,7.848734,1.677788,35.992584,164.700165,1.027925,5.667355,0.700800,UL/LL,2.535484,MAT1,0.509013,0.325061,0.432439
4,63.276463,1.643589,4.984297,1.472298,176.147232,97.454910,1.950803,8.037651,0.171457,UL,12.121090,MAT1,3.228160,2.272100,5.026540
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,30.864220,1.438606,7.849435,0.880910,144.688568,176.156158,1.703722,6.996622,0.101007,UL/LL,8.208504,MAT3,0.000000,0.276229,0.954831
119996,27.910500,1.668053,9.830630,2.133531,43.963165,12.028656,1.757961,5.716489,0.438129,UL,14.665459,MAT3,0.146325,0.219746,0.386970
119997,31.667023,1.544525,9.490417,1.800824,2.587280,149.320679,1.534479,9.091174,0.755396,UL/LL,5.883575,MAT3,0.145930,0.144822,0.378877
119998,54.257088,1.466301,7.363016,0.988127,109.062653,136.212616,2.095271,1.030856,0.215594,UL/LL,13.879539,MAT3,0.229571,4.113610,1.320460
119999,14.706306,1.501457,1.433328,0.851408,167.422028,56.759491,1.116365,9.044919,0.668719,UL,10.578758,MAT3,0.000000,0.000000,0.000000

In [6]:
Dataset_cleaned.isna().any()

Pin_D               False
R_DextDint          False
Male_Dt             False
Male_RoD            False
angle_env_reduc0    False
angle_env_reduc1    False
Female_RoD          False
Female_Dt           False
pin_doD             False
TypeLC              False
gap                 False
mat                 False
RF_Lug1             False
RF_Lug2             False
RF_Pin              False
dtype: bool

#### 4.2 Managing Outliers

In [7]:
from data_cleansing.manage_outliers import filter_outliers
Dataset_cleaned = filter_outliers(workflow, Dataset_cleaned)

Setting current step ['metadata', 'Data_Cleansing', 'Managing_Outliers']
None [{'name': 'RF_Lug1', 'range': {'min': 0.1, 'max': 10.0}}, {'name': 'RF_Lug2', 'range': {'min': 0.1, 'max': 10.0}}, {'name': 'RF_Pin', 'range': {'min': 0.1, 'max': 10.0}}]
{'name': 'RF_Lug1', 'range': {'min': 0.1, 'max': 10.0}} (98690, 15)
{'name': 'RF_Lug2', 'range': {'min': 0.1, 'max': 10.0}} (93452, 15)
{'name': 'RF_Pin', 'range': {'min': 0.1, 'max': 10.0}} (90089, 15)

In [8]:
JSON(workflow.get_step())

### Save Data

In [9]:
outputFilename =workflow.config['job_name'] + '_Dataset_cleaned.csv'
workflow.save_data(Dataset_cleaned,  outputFilename)

File /home/c05279/Pipelines/Training/working_pipeline/data/TRAINING_1_Dataset_cleaned.csv already exists

In [10]:
workflow.save_metadata()

Saved Metadata: metadata_TRAINING_1.json